name: Bug Report
description: Make a report on any bugs you've found.
title: "[BUG]: "
labels: ["bug"]
assignees:
  - Blockyheadman

body:
  - type: input
    id: describe
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: "Ex: When I try to do .. it does .."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the bug.
      placeholder: 
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior.
      placeholder: I expected it to ...
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Desktop OS
      description: What OS (Operating System) are you running?
      options:
        - Windows
        - macOS
        - X11/Linux
        - Android
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Additional Context
      description: Please add any extra context regarding the bug.
      placeholder: Link to additional resources here. Videos and images can be attached here too.
    validations:
      required: false
