blank_issues_enabled: false
contact_links:
  - name: Share an app or cahnges you made
    url: https://github.com/Blockyheadman/BlockyOS/discussions
    about: Please share your projects here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
