name: Feature Request
description: Suggest ideas and they could be put in!
title: "[FEATURE REQUEST]: "
labels: ["enhancement"]
assignees:
  - Blockyheadman

body:
  - type: textarea
    id: problem
    attributes:
      label: Is the feature request related to a problem you have?
      description: A clear and concise description of what the problem is
      placeholder: "Ex: I'm always frustrated when ..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe a solution you'd like.
      description: How can we get in touch with you if we need more info?
      placeholder: "Ex: You could add a button that ..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe any alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "Ex: I've also thought of adding a ..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Any additional context?
      description: Add any other context or screenshots about the feature request here.
      placeholder: Link any extra resources here as well. Images and videos can be added here too.
    validations:
      required: false
